version: '3.3'

services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    image: docker.io/maamun/backend-docker:v1.0.0
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - yolo-project-network
  
  client:
    image: docker.io/maamun/client-docker:v1.0.0
    ports:
      - "3000:3000"
    networks:
      - yolo-project-network
    depends_on:
      - server
networks:
  yolo-project-network:
    driver: bridge


